name: Build and Test the Degrading Counter Redis Module

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Clone Redis Repository
        run: |
          git clone https://github.com/redis/redis.git redis-sdk
          cd redis-sdk
          git checkout 7.4.1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make

      - name: Install .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build Module
        run: make REDIS_SRC=./redis-sdk/src

      - name: Copy Compiled Module
        run: cp degrading-counter.so module_unit_tests/.

      - name: Run Tests
        run: dotnet test module_unit_tests/module_unit_tests.csproj

